name: Key Vault / Test

on:
  workflow_dispatch:
  schedule:
    # At 21:00 every night
    - cron: '0 21 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Azure login with SP
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUBSCRIPTION_CREDENTIALS }}

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x ./kv-secret-scan.sh ./notify.sh

      - name: Execute task
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: bash ./kv-secret-scan.sh -s ${{ secrets.AZURE_SUBSCRIPTION_NAME }} -q
